#include "fabm_driver.h"
!#ifdef _FABM_F2003_
! --------------------------------------------
! Size- & distribution based ctenophore model
! kai wirtz Apr 2014
! Johannes Timm July 2019
! converted to fabm 1.0 in May 2020
!
! --------------------------------------------
!#include fabm_version.h
!#if _FABM_API_VERSION_ < 1
!#  error You need FABM 1.0 or later
!#endif

module hzg_ctenophore_jt
  !
  ! !USES:
  use fabm_types
  use fabm_driver
  implicit none

  !public flags for communication with fabm-driver/time-loop
  !character(len=80),   public      ::  jelly_timestr
  !integer,             public      ::  OutJellyRGR, CalcJellyRGR
  public grazkinetics

  private
  ! HZG model types
  !type type_diff
  ! real(rk) :: mu, dmudl, d2mudl2, dmudV, dsinkdl, dsinkdp, d2mudl2_d, dmu_d
  !end type
  integer   :: number_of_boxes=1
  real(rk)  :: i13sig
  real(rk)  :: relC, fC
  !#SP0
  !!----------------------------------------------------------------------
  !! this code is generated by a parser  (conv_nml_fabm.c by kai wirtz)
  !!----------------------------------------------------------------------
  ! --- HZG model types
  type type_jelly_var
     real(rk) :: Biomass_PleurobrachiaPileus,Size_PleurobrachiaPileus,Biomass_Beroe,Size_Beroe,Biomass_Detritus,Parasites_PleurobrachiaPileus,Parasites_Beroe,BenTime
     real(rk) :: Copepods,Temperature,Biomass_Phytoplankton,Size_Copepods
  end type type_jelly_var
  type type_jelly_rhs
     real(rk) :: Biomass_PleurobrachiaPileus,Size_PleurobrachiaPileus,Biomass_Beroe,Size_Beroe,Biomass_Detritus,Parasites_PleurobrachiaPileus,Parasites_Beroe,BenTime
  end type type_jelly_rhs
  ! standard fabm model types
  type,extends(type_base_model),public :: type_hzg_ctenophore_jt
     type (type_state_variable_id)        :: id_Biomass_PleurobrachiaPileus,id_Size_PleurobrachiaPileus,id_Biomass_Beroe,id_Size_Beroe,id_Biomass_Detritus,id_Parasites_PleurobrachiaPileus,id_Parasites_Beroe,id_BenTime
     type (type_dependency_id)            :: id_Copepods, id_Size_Copepods
     type (type_dependency_id)            :: id_Temperature
     type (type_dependency_id)            :: id_Biomass_Phytoplankton
     type (type_diagnostic_variable_id)   :: id_prod_Be, id_Mort_Be, id_fA_Be, id_Imax_Be, id_optimal_prey_size_Be,id_optimal_prey_size_Pp, id_optimal_prey_size_Cop, id_prod_Pp, id_Mort_Pp, id_fA_Pp, id_Imax_Pp
     type (type_diagnostic_variable_id) ::id_mort_P_Be, id_mort_S_Be, id_mort_R_Be, id_mort_G_Be, id_mort_J_Be, id_mort_T_Be, id_somgrowth_Be, id_recruit_Be, id_paras_dl_Be, id_som_dl_Be, id_turb_dl_Be, id_init_dl_Be, id_graz_dl_Be, id_sen_dl_Be, id_prod_dl_Be, id_resp_dl_Be, id_dl_prey_Be, id_dl_pred_Be, id_al_Im_Be, id_mixBmass_Be, id_mixlsize_Be, id_Tdep_Be,id_mort_top_Be
     type (type_diagnostic_variable_id) ::id_mort_P_Pp, id_mort_S_Pp, id_mort_R_Pp, id_mort_G_Pp, id_mort_J_Pp, id_mort_T_Pp, id_somgrowth_Pp, id_recruit_Pp, id_paras_dl_Pp, id_som_dl_Pp, id_turb_dl_Pp, id_init_dl_Pp, id_graz_dl_Pp, id_sen_dl_Pp, id_prod_dl_Pp, id_resp_dl_Pp, id_dl_prey_Pp, id_dl_pred_Pp, id_al_Im_Pp, id_mixBmass_Pp, id_mixlsize_Pp, id_Tdep_Pp,id_mort_top_Pp,id_cnidaria
     type (type_diagnostic_variable_id) :: id_dummy1,id_dummy2,id_dummy3,id_dummy4,id_dummy5,id_dummy6,id_dummy7,id_dummy8,id_dummy9
 type (type_diagnostic_variable_id) :: id_dummy11,id_dummy12,id_dummy13,id_dummy14,id_dummy15,id_dummy16,id_dummy17,id_dummy18,id_dummy19
     type (type_diagnostic_variable_id) :: id_sig1,id_sig2,id_sig3,id_ObsMass1,id_ObsMass2,id_ObsMass3
     type(type_diagnostic_variable_id):: id_grazingpressure1,id_grazingpressure2,id_grazingpressure3,id_grazingpressure4,id_grazingpressure5,id_grazingpressure6,id_grazingpressure7,id_grazingpressure8,id_grazingpressure9
     real(rk) ::  Biomass_PleurobrachiaPileus_initial, Size_PleurobrachiaPileus_initial, Biomass_Beroe_initial, Size_Beroe_initial, Biomass_Detritus_initial, Parasites_PleurobrachiaPileus_initial, Parasites_Beroe_initial, BenTime_initial, Size_Copepods_initial
     real(rk) ::  Size_Adult,Size_Adult_PleurobrachiaPileus,Size_Adult_Beroe, size_offspring, lstarv, sigma, Imax_pot_star, yield, mR, mS, mP, mT, mC, mTemp, mTempT, Q10, Tc, Bcrit, relCVDens, m_predBe, optimal_prey_size_adult_PleurobrachiaPileus, optimal_prey_size_adult_Beroe, optimal_prey_size_adult_Copepod, immigr, rDet, rParasite, fTDmort, m_pcap, mDisturb, Temperature_Change_Rate, Copepod_Temperature_Change_Rate
     logical  ::  TransectOn, SizeDynOn, LowPassOn, OptionOn, TECopepodshysOn, TemperatureExp,ConstMortExp,CopExp,LowTempMort
     real(rk):: Size_observable
   contains
     !   Model procedures
     procedure :: initialize
     procedure :: do
  end type type_hzg_ctenophore_jt

  !
  ! !PRIVATE DATA MEMBERS:
  real(rk), parameter :: secs_pr_day = 86400.0_rk
  !EOP
  !!--------------------------------------------------------------------

contains
  !> @brief initializes the model
  !! @details here the maecs namelists are read and assigned respectively in the model type (self),
  !! state & diagnostic variables are registered in FABM and dependencies are imported from FABM
  !>
  !> **Model parameters, descriptions and corresponding symbols used in formulas:**
  ! initial values
  !> \describepar{TransectOn   ,    , mixing between coastal transect boxes, .false. }
  !> \describepar{SizeDynOn    ,     , life stage cycling enabled, .true. }
  !> \describepar{LowPassOn    ,     , filter high frequency in forcing, .true. }
  !> \describepar{OptionOn     ,      , generic, .false. }
  !> \describepar{TECopepodshysOn   ,    , size dependency in mortality,  }
  ! other parameters
  !> \describepar{Size_Adult           , \ell_A           , adult ctenophore size        , 2.0 log(ESD/mm)}
  !> \describepar{size_offspring           , \ell_0           , offspring size, -1.2 log(ESD/mm)}
  !> \describepar{lstarv       , \ell_S       , minimum starvation size, 2. log(ESD/mm)}
  !> \describepar{sigma        , \sigma'        , log-size specific std deviation , 1. log(ESD/mm)^2}
  !> \describepar{Imax_pot_star     , I_\mathrm{max}^*     , maximum ingestion rate for ideal consumer, prey, T, and food , 173. 1/d}
  !> \describepar{yield        , y_0        , assimilation efficiency, 0.4 }
  !> \describepar{mR           , m_R^0           , Temperature dependent, natural mortality rate , 0.02 1/d}
  !> \describepar{mS           , m_S^0           , Biomass_Phytoplanktonsiological mortality under senescence , 3.E-2 1/d}
  !> \describepar{mP           , m_P^0           , density dependent mortality rate (parasites), 1.6E-5 1/d.µg-C/L}
  !> \describepar{mT           , m_{T}^0           , mortality due to Biomass_Phytoplanktonsical damage (turbulence) 0.028, 0. 1/d}
  !> \describepar{Q10          , Q_{10}          , rate increase at 10C Temperature rise, 2. }
  !> \describepar{Tc           , ^o$C] $T_c           , critical threshold Temperature, 4.5 $^o$C}
  !> \describepar{Bcrit        , B^*        , minimal prey biomass (Holling-III) , 25. µg-C/L}
  !> \describepar{relCVDens    , R_\rho    , C-biovolume density ratio non-gelatinous/gelatinous plankton, 120.0 µg-C/L}
  !> \describepar{m_predBe     , m_\mathrm{top}     , loss rate of Beroe due to top-predator , 0. 1/d}
  !> \describepar{optimal_prey_size_adult_PleurobrachiaPileus     , \lcsize_\mathrm{opt,Pp}^A     , optimal prey size adult P.pileus , -0.6 }
  !> \describepar{optimal_prey_size_adult_Beroe     , \lcsize_\mathrm{opt,Be}^A     , optimal prey size adult Beroe , 2. }
  !> \describepar{immigr       , \no_div_zero_epsilon_\mathrm{in}       , migration mass inflow rate , 5e-06 µg-C/L.d}
  !> \describepar{rDet         , r_\mathrm{Det}         , detritus turnover rate , 0.05 1/d}
  !> \describepar{rParasite    , r_\mathrm{Pars}    , turnover parasite dynamics, 1. }
  !> \describepar{fTDmort      , f_0      , warm Temperature detritus ''feed-back''   , 0.5 }
  !> \describepar{m_pcap       ,        , dependency of parasite dynamics on host/detritus biomass, 25. }
  !> \describepar{mDisturb     , B_\mathrm{cd}     , critical mass concentration detection disturbance   , 3. µg-C/L}
  !> \describepar{Temperature_Change_Rate       , \Delta T       , global Temperature change    , 0. ^oC}
  !> \describepar{Copepod_Temperature_Change_Rate     , \Delta_{Copepods}     , correlation Copepodsepod vs. Temperature change    , 0. µg-C/L/^oC}

  subroutine initialize(self, configunit)

    class (type_hzg_ctenophore_jt), intent(inout), target :: self
    integer,                  intent(in)            :: configunit
    !
    ! !LOCAL VARIABLES:
    integer    :: namlst=19
    !!------- Initial values of model jelly ------- 
    !> \describepar{Biomass_PleurobrachiaPileus_initial , B_\mathrm{Pp} , P.Pileus biomass, 3E-2 µg-C/L}
    !> \describepar{Size_PleurobrachiaPileus_initial , \ell_\mathrm{Pp} , P.Pileus mean log size, 1.4 log(ESD/mm)}
    !> \describepar{Biomass_Beroe_initial , B_\mathrm{Be} , Beroe biomass, 0E-4 µg-C/L}
    !> \describepar{Size_Beroe_initial , \ell_\mathrm{Be} , Beroe mean log size, 1.25 log(ESD/mm)}
    !> \describepar{Biomass_Detritus_initial , \ell_\mathrm{Det} , detritus, 180. µg-C/L}
    !> \describepar{Parasites_PleurobrachiaPileus_initial , \B_\mathrm{Pars,Pp} , parasite of P.Pileus, 1. µg-C/L}
    !> \describepar{Parasites_Beroe_initial , \B_\mathrm{Pars,Be} , parasite of Beroe, 1. µg-C/L}
    !> \describepar{BenTime_initial , t , time , 0. d}
    real(rk)  :: Biomass_PleurobrachiaPileus_initial ! P.Pileus biomass
    real(rk)  :: Size_PleurobrachiaPileus_initial ! P.Pileus mean log size
    real(rk)  :: Biomass_Beroe_initial ! Beroe biomass
    real(rk)  :: Size_Beroe_initial ! Beroe mean log size
    real(rk)  :: Size_Copepods_initial  ! Copepods mean log size
    real(rk)  :: Biomass_Detritus_initial ! detritus
    real(rk)  :: Parasites_PleurobrachiaPileus_initial ! parasite of P.Pileus
    real(rk)  :: Parasites_Beroe_initial ! parasite of Beroe
    real(rk)  :: BenTime_initial ! time 
    !> describepar{Size_Adult           , \ell_A           , adult ctenophore size        , 2.0 log(ESD/mm)}
    !> describepar{size_offspring           , \ell_0           , offspring size, -1.2 log(ESD/mm)}
    !> describepar{lstarv       , \ell_S       , minimum starvation size, 2. log(ESD/mm)}
    !> describepar{sigma        , \sigma'        , log-size specific std deviation , 1. log(ESD/mm)^2}
    !> describepar{Imax_pot_star     , I_\mathrm{max}^*     , maximum ingestion rate for ideal consumer, prey, T, and food , 173. 1/d}
    !> describepar{yield        , y_0        , assimilation efficiency, 0.4 }
    !> describepar{mR           , m_R^0           , Temperature dependent, natural mortality rate , 0.02 1/d}
    !> describepar{mS           , m_S^0           , Biomass_Phytoplanktonsiological mortality under senescence , 3.E-2 1/d}
    !> describepar{mP           , m_P^0           , density dependent mortality rate (parasites), 1.6E-5 1/d.µg-C/L}
    !> describepar{mT           , m_{T}^0           , mortality due to Biomass_Phytoplanktonsical damage (turbulence) 0.028, 0. 1/d}
    !> describepar{Q10          , Q_{10}          , rate increase at 10C Temperature rise, 2. }
    !> describepar{Tc           , ^o$C] $T_c           , critical threshold Temperature, 4.5 $^o$C}
    !> describepar{Bcrit        , B^*        , minimal prey biomass (Holling-III) , 25. µg-C/L}
    !> describepar{relCVDens    , R_\rho    , C-biovolume density ratio non-gelatinous/gelatinous plankton, 120.0 µg-C/L}
    !> describepar{m_predBe     , m_\mathrm{top}     , loss rate of Beroe due to top-predator , 0. 1/d}
    !> describepar{optimal_prey_size_adult_PleurobrachiaPileus     , \lcsize_\mathrm{opt,Pp}^A     , optimal prey size adult P.pileus , -0.6 }
    !> describepar{optimal_prey_size_adult_Beroe     , \lcsize_\mathrm{opt,Be}^A     , optimal prey size adult Beroe , 2. }
    !> describepar{immigr       , \no_div_zero_epsilon_\mathrm{in}       , migration mass inflow rate , 5e-06 µg-C/L.d}
    !> describepar{rDet         , r_\mathrm{Det}         , detritus turnover rate , 0.05 1/d}
    !> describepar{rParasite    , r_\mathrm{Pars}    , turnover parasite dynamics, 1. }
    !> describepar{fTDmort      , f_0      , warm Temperature detritus ''feed-back''   , 0.5 }
    !> describepar{m_pcap       ,        , dependency of parasite dynamics on host/detritus biomass, 25. }
    !> describepar{mDisturb     , B_\mathrm{cd}     , critical mass concentration detection disturbance   , 3. µg-C/L}
    !> describepar{Temperature_Change_Rate       , \Delta T       , global Temperature change    , 0. ^oC}
    !> describepar{Copepod_Temperature_Change_Rate     , \Delta_{Copepods}     , correlation Copepodsepod vs. Temperature change    , 0. µg-C/L/^oC}
    !!------- Parameters from nml-list jelly_pars ------- 
    real(rk) :: Size_Observable
    real(rk)  :: Size_Adult_PleurobrachiaPileus           ! adult ctenophore size    
    real(rk)  :: Size_Adult_Beroe           ! adult ctenophore size        
    real(rk)  :: size_offspring           ! offspring size
    real(rk)  :: lstarv       ! minimum starvation size
    real(rk)  :: sigma        ! log-size specific std deviation 
    real(rk)  :: Imax_pot_star     ! maximum ingestion rate for ideal consumer, prey, T, and food 
    real(rk)  :: yield        ! assimilation efficiency
    real(rk)  :: mR           ! Temperature dependent, natural mortality rate 
    real(rk)  :: mS           ! Biomass_Phytoplanktonsiological mortality under senescence 
    real(rk)  :: mP           ! density dependent mortality rate (parasites)
    real(rk)  :: mT           ! mortality due to Biomass_Phytoplanktonsical damage (turbulence) 0.028
    real(rk)  :: mC           ! constant background mortalilty (size agnostic)
    real(rk)  :: mTemp        ! constant Temperature mortalilty (size agnostic)
    real(rk)  :: mTempT       ! constant Temperature mortalilty threshold(size agnostic)
    real(rk)  :: Q10          ! rate increase at 10C Temperature rise
    real(rk)  :: Tc           ! critical threshold Temperature
    real(rk)  :: Bcrit        ! minimal prey biomass (Holling-III) 
    real(rk)  :: relCVDens    ! C-biovolume density ratio non-gelatinous/gelatinous plankton
    real(rk)  :: m_predBe     ! loss rate of Beroe due to top-predator 
    real(rk)  :: optimal_prey_size_adult_PleurobrachiaPileus     ! optimal prey size adult P.pileus 
    real(rk)  :: optimal_prey_size_adult_Beroe     ! optimal prey size adult Beroe
    real(rk)  :: optimal_prey_size_adult_Copepod !optimal prey size adult Copepods 
    real(rk)  :: immigr       ! migration mass inflow rate 
    real(rk)  :: rDet         ! detritus turnover rate 
    real(rk)  :: rParasite    ! turnover parasite dynamics
    real(rk)  :: fTDmort      ! warm Temperature detritus ''feed-back''   
    real(rk)  :: m_pcap       ! dependency of parasite dynamics on host/detritus biomass
    real(rk)  :: mDisturb     ! critical mass concentration detection disturbance   
    real(rk)  :: Temperature_Change_Rate       ! global Temperature change    
    real(rk)  :: Copepod_Temperature_Change_Rate     ! correlation Copepodsepod vs. Temperature change    
    !!------- Switches for configuring model structure -------
    logical   :: TransectOn   ! mixing between coastal transect boxes
    logical   :: SizeDynOn    ! life stage cycling enabled
    logical   :: LowPassOn    ! filter high frequency in forcing
    logical   :: OptionOn     ! generic
    logical   :: TECopepodshysOn   ! size dependency in mortality
    logical   :: TemperatureExp !Temperature Experiment
    logical   :: ConstMortExp !Constant mortalilty experient
    logical   :: CopExp !Constant mortalilty experient
    logical   :: LowTempMort !Constant mortalilty experient

    !namelist /jelly_init/ &
    !     Biomass_PleurobrachiaPileus_initial, Size_PleurobrachiaPileus_initial, Biomass_Beroe_initial, Size_Beroe_initial, Biomass_Detritus_initial, &
    !     Parasites_PleurobrachiaPileus_initial, Parasites_Beroe_initial, BenTime_initial

!    namelist /jelly_pars/ &
!         Size_Observable,Size_Adult, size_offspring, lstarv, sigma, Imax_pot_star, yield, mR, mS, mP, mT, Q10, Tc, Bcrit, relCVDens, m_predBe, &
!         optimal_prey_size_adult_PleurobrachiaPileus, optimal_prey_size_adult_Beroe, immigr, rDet, rParasite, fTDmort, m_pcap, mDisturb, Temperature_Change_Rate, &
!         Copepod_Temperature_Change_Rate

 !   namelist /jelly_switch/ &
 !        TransectOn, SizeDynOn, LowPassOn, OptionOn, TECopepodshysOn

    Biomass_PleurobrachiaPileus_initial = 3E-2_rk            ! µg-C/L
    Size_PleurobrachiaPileus_initial = 1.4_rk             ! log(ESD/mm)
    Biomass_Beroe_initial = 0E-4_rk            ! µg-C/L
    Size_Beroe_initial = 1.25_rk            ! log(ESD/mm)
    Size_Copepods_initial = -0.8_rk            ! log(ESD/mm) (previously -0.6)
    Biomass_Detritus_initial = 180._rk            ! µg-C/L
    Parasites_PleurobrachiaPileus_initial = 25.0_rk              ! µg-C/L
    Parasites_Beroe_initial = 2.5_rk              ! µg-C/L
    BenTime_initial = 0._rk              ! d
    Size_Adult_PleurobrachiaPileus           = 2.0_rk             ! log(ESD/mm)
    Size_Adult_Beroe           = 2.0_rk             ! log(ESD/mm)
    size_offspring           = -1.2_rk            ! log(ESD/mm)
    lstarv       = 2._rk              ! log(ESD/mm)
    sigma        = 1._rk              ! log(ESD/mm)^2
    Imax_pot_star     = 173._rk            ! 1/d
    yield        = 0.4_rk             ! 
    mR           = 0.02_rk            ! 1/d
    mS           = 3.E-2_rk           ! 1/d
    mP           = 1.6E-5_rk          ! 1/d.µg-C/L
    mT           = 0._rk              ! 1/d
    mC           = 0.01_rk              ! 1/d
    mTemp        = 0.01_rk            ! 1/d
    mTempT        = 6.0_rk            ! Celsius
    Q10          = 2._rk              ! 
    Tc           = 4.5_rk             ! $^o$C
    Bcrit        = 25._rk             ! µg-C/L
    relCVDens    = 120.0_rk           ! µg-C/L
    m_predBe     = 0._rk              ! 1/d
    optimal_prey_size_adult_PleurobrachiaPileus     = -0.6_rk            ! 
    optimal_prey_size_adult_Beroe     = 2._rk              ! 
    optimal_prey_size_adult_Copepod = -3.5_rk
    immigr       = 5e-06_rk           ! µg-C/L.d
    rDet         = 0.05_rk            ! 1/d
    rParasite    = 1._rk              ! 
    fTDmort      = 0.5_rk             ! 
    m_pcap       = 25._rk             ! 
    mDisturb     = 3._rk              ! µg-C/L
    Temperature_Change_Rate       = 0._rk              ! ^oC
    Copepod_Temperature_Change_Rate     = 0._rk              ! µg-C/L/^oC


    !--------- read namelists --------- 
    write(0,*) ' read namelists ....'
    !open(namlst,file='jelly_init.nml',status='old')
    !read(namlst,nml=jelly_init,err=90,end=99)
    !open(namlst,file='jelly_pars.nml',status='old')
    !read(namlst,nml=jelly_pars,err=91,end=100)
    !open(namlst,file='jelly_switch.nml',status='old')
    !read(namlst,nml=jelly_switch,err=92,end=101)
    ! Store parameter values in our own derived type
    ! NB: all rates must be provided in values per day,
    ! and are converted here to values per second.

    !!------- logical parameters: switches  -------
    call self%get_parameter(self%TransectOn,    'TransectOn',    default=TransectOn)
    call self%get_parameter(self%SizeDynOn,     'SizeDynOn',     default=SizeDynOn)
    call self%get_parameter(self%LowPassOn,     'LowPassOn',     default=LowPassOn)
    call self%get_parameter(self%OptionOn,      'OptionOn',      default=OptionOn)
    call self%get_parameter(self%TECopepodshysOn,    'TECopepodshysOn',    default=TECopepodshysOn)
    call self%get_parameter(self%TemperatureExp,    'TemperatureExp',    default=TemperatureExp)
    call self%get_parameter(self%ConstMortExp,    'ConstMortExp',    default=ConstMortExp)
    call self%get_parameter(self%CopExp,    'CopExp',    default=CopExp)
    call self%get_parameter(self%LowTempMort,    'LowTempMort',    default=LowTempMort)
    !!------- model parameters from nml-list jelly_init ------- 
    call self%get_parameter(self%Biomass_PleurobrachiaPileus_initial ,'Biomass_PleurobrachiaPileus_initial',  default=Biomass_PleurobrachiaPileus_initial)
    call self%get_parameter(self%Size_PleurobrachiaPileus_initial ,'Size_PleurobrachiaPileus_initial',  default=Size_PleurobrachiaPileus_initial)
    call self%get_parameter(self%Biomass_Beroe_initial ,'Biomass_Beroe_initial',  default=Biomass_Beroe_initial)
    call self%get_parameter(self%Size_Beroe_initial ,'Size_Beroe_initial',  default=Size_Beroe_initial)
    call self%get_parameter(self%Biomass_Detritus_initial ,'Biomass_Detritus_initial',  default=Biomass_Detritus_initial)
    call self%get_parameter(self%Parasites_PleurobrachiaPileus_initial ,'Parasites_PleurobrachiaPileus_initial',  default=Parasites_PleurobrachiaPileus_initial)
    call self%get_parameter(self%Parasites_Beroe_initial ,'Parasites_Beroe_initial',  default=Parasites_Beroe_initial)
    call self%get_parameter(self%BenTime_initial ,'BenTime_initial',  default=BenTime_initial)
    call self%get_parameter(self%Size_Copepods_initial ,'Size_Copepods_initial',  default=Size_Copepods_initial)

    !!------- model parameters from nml-list jelly_pars -------
    call self%get_parameter(self%Size_Adult_PleurobrachiaPileus           ,'Size_Adult_PleurobrachiaPileus',            default=Size_Adult_PleurobrachiaPileus)
    call self%get_parameter(self%Size_Adult_Beroe           ,'Size_Adult_Beroe',            default=Size_Adult_Beroe)
    call self%get_parameter(self%size_offspring           ,'size_offspring',            default=size_offspring)
    call self%get_parameter(self%lstarv       ,'lstarv',        default=lstarv)
    call self%get_parameter(self%sigma        ,'sigma',         default=sigma)
    call self%get_parameter(self%Imax_pot_star     ,'Imax_pot_star',      default=Imax_pot_star)
    call self%get_parameter(self%yield        ,'yield',         default=yield)
    call self%get_parameter(self%mR           ,'mR',            default=mR)
    call self%get_parameter(self%mS           ,'mS',            default=mS)
    call self%get_parameter(self%mP           ,'mP',            default=mP)
    call self%get_parameter(self%mT           ,'mT',            default=mT)
    call self%get_parameter(self%mC           ,'mC',            default=mC)
    call self%get_parameter(self%mTemp        ,'mTemp',         default=mTemp)
    call self%get_parameter(self%mTempT       ,'mTempT',        default=mTempT)
    call self%get_parameter(self%Q10          ,'Q10',           default=Q10)
    call self%get_parameter(self%Tc           ,'Tc',            default=Tc)
    call self%get_parameter(self%Bcrit        ,'Bcrit',         default=Bcrit)
    call self%get_parameter(self%relCVDens    ,'relCVDens',     default=relCVDens)
    call self%get_parameter(self%m_predBe     ,'m_predBe',      default=m_predBe)
    call self%get_parameter(self%optimal_prey_size_adult_PleurobrachiaPileus,'optimal_prey_size_adult_PleurobrachiaPileus',      default=optimal_prey_size_adult_PleurobrachiaPileus)
    call self%get_parameter(self%optimal_prey_size_adult_Beroe,'optimal_prey_size_adult_Beroe',      default=optimal_prey_size_adult_Beroe)
    call self%get_parameter(self%optimal_prey_size_adult_Copepod,'real(rk)::optimal_prey_size_adult_Copepod',default=optimal_prey_size_adult_Copepod)
    call self%get_parameter(self%immigr       ,'immigr',        default=immigr)
    call self%get_parameter(self%rDet         ,'rDet',          default=rDet)
    call self%get_parameter(self%rParasite    ,'rParasite',     default=rParasite)
    call self%get_parameter(self%fTDmort      ,'fTDmort',       default=fTDmort)
    call self%get_parameter(self%m_pcap       ,'m_pcap',        default=m_pcap)
    call self%get_parameter(self%mDisturb     ,'mDisturb',      default=mDisturb)
    call self%get_parameter(self%Temperature_Change_Rate       ,'Temperature_Change_Rate',        default=Temperature_Change_Rate)
    call self%get_parameter(self%Copepod_Temperature_Change_Rate     ,'Copepod_Temperature_Change_Rate',      default=Copepod_Temperature_Change_Rate)

    !!------- Register state variables  ------- 
    call self%register_state_variable(self%id_Biomass_PleurobrachiaPileus,  'Biomass_PleurobrachiaPileus','µg-C/L','P.Pileus biomass Biomass_PleurobrachiaPileus', &
         Biomass_PleurobrachiaPileus_initial, minimum=_ZERO_, no_river_dilution=.true. )
    call self%register_state_variable(self%id_Size_PleurobrachiaPileus,  'Size_PleurobrachiaPileus','log(ESD/mm)','P.Pileus mean log size Size_PleurobrachiaPileus', &
         Size_PleurobrachiaPileus_initial, minimum=-3.0d0, no_river_dilution=.true. )
    call self%register_state_variable(self%id_Biomass_Beroe,  'Biomass_Beroe','µg-C/L','Beroe biomass Biomass_Beroe', &
         Biomass_Beroe_initial, minimum=_ZERO_, no_river_dilution=.true. )
    call self%register_state_variable(self%id_Size_Beroe,  'Size_Beroe','log(ESD/mm)','Beroe mean log size Size_Beroe', &
         Size_Beroe_initial, minimum=-3.0d0, no_river_dilution=.true. )
    call self%register_state_variable(self%id_Biomass_Detritus, 'Biomass_Detritus','µg-C/L','detritus Biomass_Detritus', &
         Biomass_Detritus_initial, minimum=_ZERO_, no_river_dilution=.true. )
    call self%register_state_variable(self%id_Parasites_PleurobrachiaPileus, 'Parasites_PleurobrachiaPileus','µg-C/L','parasite of P.Pileus Parasites_PleurobrachiaPileus', &
         Parasites_PleurobrachiaPileus_initial, minimum=_ZERO_, no_river_dilution=.true. )
    call self%register_state_variable(self%id_Parasites_Beroe, 'Parasites_Beroe','µg-C/L','parasite of Beroe Parasites_Beroe', &
         Parasites_Beroe_initial, minimum=_ZERO_, no_river_dilution=.true. )
    call self%register_state_variable(self%id_BenTime, 'BenTime','d','time  BenTime', &
         BenTime_initial, minimum=_ZERO_, no_river_dilution=.true. )

    !!------- Register diagnostic variables  ------- 

 

    call self%register_diagnostic_variable(self%id_prod_Be, 'prod_Be','1/d', 'secondary production rate Beroe prod_Be', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_Mort_Be, 'Mort_Be','1/d', 'mortality rate of Beroe Mort_Be', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_fA_Be,   'fA_Be','1/d', 'relative propotion adults Beroe fA_Be', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_Imax_Be, 'Imax_Be','1/d', 'maximum ingestion rate adult Beroe Imax_Be', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_optimal_prey_size_Be, 'optimal_prey_size_Be','1/d', 'optimum prey size Beroe optimal_prey_size_Be', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_optimal_prey_size_pp, 'optimal_prey_size_Pp','1/d', 'optimum prey size Beroe optimal_prey_size_Pp', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_prod_Pp, 'prod_Pp','1/d', 'secondary production rate P pileus prod_Pp', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_Mort_Pp, 'Mort_Pp','1/d', 'mortality rate of P pileus Mort_Pp', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_fA_Pp,   'fA_Pp','1/d', 'relative proportion adults P pileus fA_Pp', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_Imax_Pp, 'Imax_Pp','1/d', 'maximum ingestion rate adult Beroe Imax_Pp', &
         output=output_instantaneous)

    call self%register_diagnostic_variable(self%id_mort_P_Be,  'mort_P_Be','1/d', 'density dependent mortality parasites mort_P_Be', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_mort_S_Be,  'mort_S_Be','1/d', 'Biomass_Phytoplanktonsiological adult mortality rate mort_S_Be', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_mort_R_Be,  'mort_R_Be','1/d', 'Temperature dependent mortality mort_R_Be', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_mort_G_Be,  'mort_G_Be','1/d', 'top-predation mort_G_Be', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_mort_top_Be,  'mort_top_Be','1/d', 'top-predation mort_top_Be', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_mort_J_Be,  'mort_J_Be','1/d', 'juvenile mortality mort_J_Be', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_mort_T_Be,  'mort_T_Be','1/d', 'damaging effect of turbulence mort_T_Be', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_somgrowth_Be, 'somgrowth_Be','1/d', 'somatic growth rate somgrowth_Be', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_recruit_Be, 'recruit_Be','1/d', 'egg production rate  recruit_Be', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_paras_dl_Be, 'paras_dl_Be','1/d', 'marginal size shift parasites paras_dl_Be', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_som_dl_Be,  'som_dl_Be','1/d', 'marginal size shift due to promotion som_dl_Be', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_turb_dl_Be, 'turb_dl_Be','1/d', 'marginal size shift due to physical damage turb_dl_Be', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_init_dl_Be, 'init_dl_Be','1/d', 'marginal size shift due to egg production init_dl_Be', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_graz_dl_Be, 'graz_dl_Be','1/d', 'marginal size shift due to selective grazing graz_dl_Be', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_sen_dl_Be,  'sen_dl_Be','1/d', 'marginal size shift due to starvation sen_dl_Be', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_prod_dl_Be, 'prod_dl_Be','1/d', 'marginal size shift due to production prod_dl_Be', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_resp_dl_Be, 'resp_dl_Be','1/d', 'marginal size shift due to respiration resp_dl_Be', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_dl_prey_Be, 'dl_prey_Be','1/d', 'size difference to prey dl_prey_Be', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_dl_pred_Be, 'dl_pred_Be','1/d', 'size difference to pred dl_pred_Be', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_al_Im_Be,   'al_Im_Be','1/d', 'size scaling exponent Imax al_Im_Be', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_mixBmass_Be, 'mixBmass_Be','1/d', 'mass exchange rate Coast-HR-Offshore mixBmass_Be', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_mixlsize_Be, 'mixlsize_Be','1/d', 'trait exchange rate Coast-HR-Offshore mixlsize_Be', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_Tdep_Be,    'Tdep_Be','1/d', 'Temperature dependency Tdep_Be', &
         output=output_instantaneous)


    call self%register_diagnostic_variable(self%id_mort_P_Pp,  'mort_P_Pp','1/d', 'density dependent mortality parasites mort_P_Pp', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_mort_S_Pp,  'mort_S_Pp','1/d', 'Biomass_Phytoplanktonsiological adult mortality rate mort_S_Pp', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_mort_R_Pp,  'mort_R_Pp','1/d', 'Temperature dependent mortality mort_R_Pp', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_mort_G_Pp,  'mort_G_Pp','1/d', 'top-predation mort_G_Pp', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_mort_J_Pp,  'mort_J_Pp','1/d', 'juvenile mortality mort_J_Pp', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_mort_T_Pp,  'mort_T_Pp','1/d', 'damaging effect of turbulence mort_T_Pp', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_mort_top_Pp,  'mort_top_Pp','1/d', 'top-predation mort_top_Pp', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_somgrowth_Pp, 'somgrowth_Pp','1/d', 'somatic growth rate somgrowth_Pp', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_recruit_Pp, 'recruit_Pp','1/d', 'egg production rate recruit_Pp', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_paras_dl_Pp, 'paras_dl_Pp','1/d', 'marginal size shift parasites paras_dl_Pp', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_som_dl_Pp,  'som_dl_Pp','1/d', 'marginal size shift due to promotion som_dl_Pp', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_turb_dl_Pp, 'turb_dl_Pp','1/d', 'marginal size shift due to physical damage turb_dl_Pp', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_init_dl_Pp, 'init_dl_Pp','1/d', 'marginal size shift due to egg production init_dl_Pp', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_graz_dl_Pp, 'graz_dl_Pp','1/d', 'marginal size shift due to selective grazing graz_dl_Pp', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_sen_dl_Pp,  'sen_dl_Pp','1/d', 'marginal size shift due to starvation sen_dl_Pp', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_prod_dl_Pp, 'prod_dl_Pp','1/d', 'marginal size shift due to production prod_dl_Pp', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_resp_dl_Pp, 'resp_dl_Pp','1/d', 'marginal size shift due to respiration resp_dl_Pp', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_dl_prey_Pp, 'dl_prey_Pp','1/d', 'size difference to prey dl_prey_Pp', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_dl_pred_Pp, 'dl_pred_Pp','1/d', 'size difference to pred dl_pred_Pp', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_al_Im_Pp,   'al_Im_Pp','1/d', 'size scaling exponent Imax al_Im_Pp', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_mixBmass_Pp, 'mixBmass_Pp','1/d', 'mass exchange rate Coast-HR-Offshore mixBmass_Pp', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_mixlsize_Pp, 'mixlsize_Pp','1/d', 'trait exchange rate Coast-HR-Offshore mixlsize_Pp', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_Tdep_Pp,    'Tdep_Pp','1/d', 'Temperature dependency Tdep_Pp', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_cnidaria,    'cnidaria','1/d', 'cnidaria', &
         output=output_instantaneous)

    call self%register_diagnostic_variable(self%id_dummy1,    'dummy1','1/d', 'Dummy1', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_dummy2,    'dummy2','1/d', 'Dummy2', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_dummy3,    'dummy3','1/d', 'Dummy3', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_dummy4,    'dummy4','1/d', 'Dummy4', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_dummy5,    'dummy5','1/d', 'Dummy5', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_dummy6,    'dummy6','1/d', 'Dummy6', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_dummy7,    'dummy7','1/d', 'Dummy7', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_dummy8,    'dummy8','1/d', 'Dummy8', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_dummy9,    'dummy9','1/d', 'Dummy9', &
         output=output_instantaneous)


    call self%register_diagnostic_variable(self%id_dummy11,    'dummy11','1/d', 'Dummy11', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_dummy12,    'dummy12','1/d', 'Dummy12', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_dummy13,    'dummy13','1/d', 'Dummy13', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_dummy14,    'dummy14','1/d', 'Dummy14', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_dummy15,    'dummy15','1/d', 'Dummy15', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_dummy16,    'dummy16','1/d', 'Dummy16', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_dummy17,    'dummy17','1/d', 'Dummy17', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_dummy18,    'dummy18','1/d', 'Dummy18', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_dummy19,    'dummy19','1/d', 'Dummy19', &
         output=output_instantaneous)


    call self%register_diagnostic_variable(self%id_grazingpressure1,    'grazingpressure1','1/d', 'grazingpressure1', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_grazingpressure2,    'grazingpressure2','1/d', 'grazingpressure2', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_grazingpressure3,    'grazingpressure3','1/d', 'grazingpressure3', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_grazingpressure4,    'grazingpressure4','1/d', 'grazingpressure4', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_grazingpressure5,    'grazingpressure5','1/d', 'grazingpressure5', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_grazingpressure6,    'grazingpressure6','1/d', 'grazingpressure6', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_grazingpressure7,    'grazingpressure7','1/d', 'grazingpressure6', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_grazingpressure8,    'grazingpressure8','1/d', 'grazingpressure6', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_grazingpressure9,    'grazingpressure9','1/d', 'grazingpressure6', &
         output=output_instantaneous)

    call self%register_diagnostic_variable(self%id_sig1,    'sig1','1/d', 'sig1', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_sig2,    'sig2','1/d', 'sig2', &
         output=output_instantaneous)

    call self%register_diagnostic_variable(self%id_sig3,    'sig3','1/d', 'sig3', &
         output=output_instantaneous)

    call self%register_diagnostic_variable(self%id_ObsMass1,    'ObsMass1','µg-C/L', 'Biomass_Observable_Beroe', &
         output=output_instantaneous)
    call self%register_diagnostic_variable(self%id_ObsMass2,    'ObsMass2','µg-C/L', 'Biomass_Observalbe_Pleurobrachia_Pileus', &
         output=output_instantaneous)

    call self%register_diagnostic_variable(self%id_ObsMass3,    'ObsMass3','µg-C/L', 'Biomass_Observalbe_Copepods', &
         output=output_instantaneous)



    !!------- Register environmental dependencies  ------- 
    !!-------------------------read in data using the imput.yaml


    !call self%register_dependency(self%id_Copepods,standard_variables%downwelling_photosynthetic_radiative_flux)
    !call self%register_dependency(self%id_Temperature,standard_variables%Temperature)
    !call self%register_dependency(self%id_Biomass_Phytoplankton,standard_variables%practical_salinity)


   call self%register_dependency(self%id_Copepods,'copepod_biom','µg-C/L','Copepod_Biomass')
   call self%register_dependency(self%id_Size_Copepods,'copepod_size','log(ESD/mm)','Copepod_Size')
   call self%register_dependency(self%id_Temperature,standard_variables%Temperature)
   call self%register_dependency(self%id_Biomass_Phytoplankton,'phy','mol-C/m3','mole_concentration_of_phytoplankton_expressed_as_carbon_in_sea_water')



    ! extra line included from parser var init_incl 
#define UNIT *1.1574074074E-5_rk

    relC    = self%Temperature_Change_Rate * self%Copepod_Temperature_Change_Rate / 29.d0
    fC      = (1.0d0+relC)/(1.d0 + relC * (1.d0 - 0.5*exp(0.5+3*relC*relC*relC)));

    return

 !   !!-------  if files are not found ...  
!90  call self%fatal_error('jelly_init','Error reading namelist jelly_init.')
!91  call self%fatal_error('jelly_init','Error reading namelist jelly_pars.')
!92  call self%fatal_error('jelly_init','Error reading namelist jelly_switch.')
!99  call self%fatal_error('jelly_init','Namelist jelly_init was not found in file.')
!100 call self%fatal_error('jelly_init','Namelist jelly_pars was not found in file.')
!101 call self%fatal_error('jelly_init','Namelist jelly_switch was not found in file.')

  end subroutine initialize

  !!----------------------------------------------------------------------
  !!   end of section generated by parser 
  !!----------------------------------------------------------------------
  ! #SP#"
  !
  !INTERFACE:
  subroutine do(self,_ARGUMENTS_DO_)
    !
    ! !INPUT PARAMETERS:
    class (type_hzg_ctenophore_jt),intent(in) :: self
    _DECLARE_ARGUMENTS_DO_
    !
    !LOCAL VARIABLES:

    type (type_jelly_var), dimension(3)       :: var
    type (type_jelly_rhs)       :: rhsv
    !type (type_diff)      :: diff,diff2
    !real(rk)              :: d2mudl2_d, dmu2=0.0_rk, mfac
    !  type (type_environment),   intent(inout)  :: environment 
    real(rk),dimension(3) :: mort_S, mort_S0, mort_T0, mort_top
    real(rk),dimension(3) :: mort_T, mort_sum, mort_const, mort_Temp
    real(rk) :: errf, eargA1,eargA2,argA1,argA2,argA3, eS0, argA5,errf1,mass_sum
    real(rk) :: lesdr, optimal_prey_sizem, detect, dummy_reused_variable2, dummy_reused_variable3, dummy_reused_variable4, dummy_reused_variable5, ft,ft2
    real(rk),dimension(3) :: somgrwth, recruit,lco, starv, dal_dl, min_dl, bound_dl
    real(rk),dimension(3) :: prod_dl, sum_dl, resp_dl,paras_dl, turb_dl
    real(rk),dimension(3) :: graz_dl, som_dl, init_dl, sen_dl,ft3
    real(rk),dimension(3):: yield_factor

    real(rk), dimension(3) :: Imax, Ingest_kernel, di_dl, di0_dl, dg_dly, dprod_dl
    real(rk), dimension(3) :: Change_of_optimal_prey_size,optimal_prey_size, graz,Temperature_dep,sig13, sig23, ksat
    real(rk), dimension(3) :: mort_graz, sig, log_size_variance_mesozoo, log_mean_size, mass, relDens
    real(rk), dimension(3) :: mort_R, mort_R0, mort_P
    real(rk), dimension(3) :: optimal_prey_size_adult,experimental_optimal_prey_size_adult, preyc, paras, fLc, m_host,rpara, pS, test0
    real(rk),dimension(3) :: Size_Adult,Size_Maturity,lavg
    real(rk), dimension(3,3):: graz_term,grazing_pressure_ji 

    real(rk) :: dl, bcrit1, preyE
    real(rk) :: fR, lm_adult, al, aff, activ, no_div_zero_eps,mean_Temperature_HR,mben,Temperaturep
    real(rk) :: dp_dB, no_age, cnidaria
    real(rk),dimension(3)::gross,prey_mass_after_selection, prey_mass_after_selection_relative_biovolume,dp_dl,affin
    real(rk), dimension(3) :: prod,fA,fObs,biomass_observable
    integer  :: ib, i, j, max_number_of_predators
    logical  :: Is_Copepod_biomass_negative, Is_Copepod_biomass_exhausted, IsMaxIng 
    logical :: TopPredationSwitch=.FALSE.!.TRUE.!.FALSE.
    logical ::Debugout=.FALSE.
    !					Be     Pp     Copepods
    ! integer  :: webtopo(3,3) = reshape((/0,1,0, 1,1,1, 0,0,0/), (/3,3/))
    !logical  :: webtopo(3,3) = reshape((/.False.,.True.,.False., .True.,.True.,.True., .False.,.False.,.False./),(/3,3/))

    logical  :: webtopo(3,3) = reshape((/.False.,.True.,.False., .True.,.True.,.True., .True.,.True.,.False./),(/3,3/))
    !  fortran organizes arrays as column major
    !  real(rk) :: inflow=2E-1, Adorm=2E-3

    ! !REVISION HISTORY:
    !  Original author(s): Kai Wirtz

    ! !DESCRIPTION:
    ! Stage-based Pleurobrachia & Beroe   Model
    !
    !EOP
    !-----------------------------------------------------------------------
    !BOC
    no_div_zero_eps      =  1E-5    ! small number epsilon that avoids division by zero
    Is_Copepod_biomass_negative    =  .false. ! scenario flag, may be changed due to forcing signal
    !***!
    IsMaxIng =  .false. ! correction of Imax-scaling at small size
    mean_Temperature_HR    =  10.2d0  ! mean HR water Temperature (only used for scenario runs)
    no_age   =  0.5d0   ! relative importance of stage independent sensitivity
    !write (*,'(A,4(I3))') 'w=',webtopo(3,1),webtopo(2,2),webtopo(1,3),webtopo(3,3)
    !if(webtopo(1,3)+webtopo(2,3)+webtopo(3,3) .gt. 0) then
    if(webtopo(1,3).or.webtopo(2,3).or.webtopo(3,3)) then
       max_number_of_predators = 3
     if (Debugout)  write (*,*) '3 predators'
    else
       max_number_of_predators = 2
    if (Debugout)  write (*,*) '2 predators'
    endif

   

    !-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

    ! Enter spatial loops (if any)
    !_FABM_LOOP_BEGIN_
    _LOOP_BEGIN_

    ! here box set-up within fabm-0D driver
    ! loop over boxes   1: HR  2: Offshore
    do ib = 1, number_of_boxes

       !#S_GET
       !---------- GET for each state variable ----------
       _GET_(self%id_Biomass_PleurobrachiaPileus, var(ib)%Biomass_PleurobrachiaPileus)  ! P.Pileus biomass in µg-C/L
       _GET_(self%id_Size_PleurobrachiaPileus, var(ib)%Size_PleurobrachiaPileus)  ! P.Pileus mean log size in log(ESD/mm)
       _GET_(self%id_Biomass_Beroe, var(ib)%Biomass_Beroe)  ! Beroe biomass in µg-C/L
       _GET_(self%id_Size_Beroe, var(ib)%Size_Beroe)  ! Beroe mean log size in log(ESD/mm)
       _GET_(self%id_Biomass_Detritus, var(ib)%Biomass_Detritus)  ! detritus in µg-C/L
       _GET_(self%id_Parasites_PleurobrachiaPileus, var(ib)%Parasites_PleurobrachiaPileus)  ! parasite of P.Pileus in µg-C/L
       _GET_(self%id_Parasites_Beroe, var(ib)%Parasites_Beroe)  ! parasite of Beroe in µg-C/L
       _GET_(self%id_BenTime, var(ib)%BenTime)  ! time  in d
       !#E_GET
       ! Retrieve current environmental conditions.
       !#S_GED
       _GET_(self%id_Copepods, var(ib)%Copepods)  ! biomass from Greve data-set
       _GET_(self%id_Size_Copepods, var(ib)%Size_Copepods)  ! biomass from Greve data-set
       _GET_(self%id_Temperature, var(ib)%Temperature)  ! Temperature HR
       _GET_(self%id_Biomass_Phytoplankton, var(ib)%Biomass_Phytoplankton)  ! Biomass_Phytoplanktontoplankton biomass HR
       !#E_GED
       

      !-------------------------for Temperature experient only No temperatures below 2.0 Celsius
      if (self%TemperatureExp) then
        if (var(ib)%Temperature<4.0d0)  then
           var(ib)%Temperature=4.0d0
          ! write (*,*)   'Temperature Experiment: Temperature capped at 1.0C' 
        end if
      end if


     if (self%CopExp) then
        if (var(ib)%Copepods<1.0d0)  then
           var(ib)%Copepods=1.0d0
           write (*,*)   'Copepod Experiment: capped at 1.0 µg-C/L' 
        end if
      end if


    end do
    !
    ! ---------- set environmental conditions for each box  -------------------
    !
    ! ib=1 HR   2: Coast  3:Offshore
    ! open water: less Copepodsepods, and reduced Temperature fluctuation
    !  var(2)%Copepods  = 1.5 * var(2)%Copepods!  var(2)%Temperature = -0.5 + 1.15*var(2)%Temperature



    cnidaria = additional_food(var(1)%BenTime)


    ! loop over boxes   1: HR  2: Offshore
    do ib = 1, number_of_boxes
       !
       ! ---------- set specific variables for each population  -------------------
       !
       ! set coefficient vectors over prey populations:  1: Beroe 2: Ppileus  3: Copepodss
       log_mean_size(1) = var(ib)%Size_Beroe  ! mean body size of population
       log_mean_size(2) = var(ib)%Size_PleurobrachiaPileus  ! 
       !log_mean_size(3) = -0.6d0        ! small Copepodsepods dominate. ! TODO: include as forcing 
       !log_mean_size(3) = self%Size_Copepods_initial        ! small Copepodsepods dominate. ! TODO: include as forcing 
       log_mean_size(3) = var(ib)%Size_Copepods

       log_size_variance_mesozoo(3) = 0.8d0         ! log-size variance of mesozooplakton
       mass(1)   = var(ib)%Biomass_Beroe  ! biomass concentration
       mass(2)   = var(ib)%Biomass_PleurobrachiaPileus
       mass(3)   = var(ib)%Copepods  ! global correction for too low prey/Copepods biomass

!------------------------------only for constant copepods
!mass(3)=35.0d0!---------constant copepods
!------------------------------


	
       !check that always some minimal number of copepods are around to aviod numerical issues/model extinction
       ! pass binary info through sign of Copepodsepod input 
       if ( mass(3) .lt. 0.0d0) then
          mass(3)= -mass(3)
          Is_Copepod_biomass_negative  = .true.
       else
          Is_Copepod_biomass_negative  = .false.
       endif

       if ( abs(mass(3)-50.) .lt. -0.0001d0 .or. abs(mass(3)-5.) .lt. -0.0001d0) then
          Is_Copepod_biomass_exhausted= .true.
         if (Debugout) write (*,'(A,3(F12.4))') 'm=',mass(1)*1E3,mass(2)*1E3,mass(3)
         if (Debugout) write (*,'(A,3(F12.4))') 'l=',log_mean_size(1),log_mean_size(2),log_mean_size(3)

       else
          Is_Copepod_biomass_exhausted = .false.
       endif

       !! scenario: Temperature change correlates with Copepods change
       !  if( abs(self%Copepod_Temperature_Change_Rate) .gt. 1E-3 .and. abs(self%Temperature_Change_Rate) .gt. 1E-3) then 
       !     mass(3) = mass(3) * fC * (1.0d0+relC*(1.d0-exp(1.d0-mass(3)/29.d0)))
       !  endif

       ! scenario: Temperature change 
       !  if(self%TECopepodshysOn  .and. (Is_Copepod_biomass_negative .or. self%Temperature_Change_Rate .gt. 0.0d0)) then 
       !      Temperaturep     = var(ib)%Temperature+self%Temperature_Change_Rate*exp((mean_Temperature_HR-var(ib)%Temperature)/(2*mean_Temperature_HR))
       !  else
       Temperaturep     = var(ib)%Temperature
       !  endif

       ! parasite states into vector
       paras(1)  = var(ib)%Parasites_Beroe
       paras(2)  = var(ib)%Parasites_PleurobrachiaPileus

       ! assignment of group specific parameters 
       ! rel. C-biovolume density ratio of non-gelatinous plankton
       relDens(1)= self%relCVDens ! Be:   jelly
       relDens(2)= self%relCVDens ! Pp:   jelly
       relDens(3)= 1.0d0          ! Copepodss: non-jelly
       ! opt-prey-size change during ontogeny

       Size_Adult(1)=self%Size_Adult_Beroe
       Size_Adult(2)=self%Size_Adult_PleurobrachiaPileus
       Size_Adult(3)=-2.0d0 !should never be used
       Size_Maturity=Size_Adult !todo: adult size is not equal to maturity in ctenophores
       experimental_optimal_prey_size_adult(1)=self%optimal_prey_size_adult_Beroe
       experimental_optimal_prey_size_adult(2)=self%optimal_prey_size_adult_PleurobrachiaPileus
       experimental_optimal_prey_size_adult(3)=self%optimal_prey_size_adult_Copepod !=-3.5d0

       Change_of_optimal_prey_size(1)= prey_development(experimental_optimal_prey_size_adult(1),self%size_offspring,self%Size_Adult_PleurobrachiaPileus)
       Change_of_optimal_prey_size(2)= prey_development(experimental_optimal_prey_size_adult(2),self%size_offspring,self%Size_Adult_Beroe)
       Change_of_optimal_prey_size(3)= prey_development(experimental_optimal_prey_size_adult(3),self%size_offspring,log_mean_size(3))

       Temperature_dep(3) = f_Temperature(self%Q10+1.0d0, Temperaturep, 0.0d0)

       ! re-gauge coefficient to apply  Imax-scaling of Wirtz JPR,2012 
       !    log(1E3/80) converts from log(micro-m) to log(mm) but accounts for much lower C-density
       ! optimum size/stage with minimal life-stage dependent mortality 
do i = 1, max_number_of_predators
       lavg(i)    = 0.5d0*(Size_Adult(i) + self%size_offspring) ! 0.4
end do
       !  loop over ctenophore populations:  1: Beroe 2: Ppileus 
       !
       ! Temperature experiment; separate effect on parasite dynamics through altered Copepodsepod/detrital mass
       !  if(self%OptionOn .and. abs(self%Copepod_Temperature_Change_Rate) .gt. 1E-3 .and. abs(self%Temperature_Change_Rate) .gt. 1E-3) then 
       !     mass(3)   =  mass(3)* fC * (1.0d0+relC*(1.d0-exp(1.d0-mass(3)/29.d0)))
       !  endif
       !  if(mass(3) .gt. 175.) mass(3) = 175.0d0
       !***!

       do i = 1, max_number_of_predators
          lco(i)       = log(1E3/relDens(i))
          optimal_prey_size(i)   = self%size_offspring + (log_mean_size(i)-self%size_offspring)*Change_of_optimal_prey_size(i) ! optimal prey size
          optimal_prey_size_adult(i)  = self%size_offspring + (Size_Adult(i)-self%size_offspring)*Change_of_optimal_prey_size(i) ! optimal prey size
          !Temperature_dep(3)fLc* * *exp(0.5*(log_mean_size(i)-lavg(i)-optimal_prey_size(i)))
          ! potential maximum ingestion rate depending on size, T, and feeding mode
          ! re-gauge log size to µm-scale used in Wirtz JPR,2012     log(1E3/80)=2.5
          !    converts from log(µm) to log(mm) but accounts for much lower C-density  
          !    lesdr     = 0.0d0
          !!    if (IsMaxIng) then
          !! correction to prevent unrealistic Imax-size dependency for juveniles (see Fig.4 Wirtz JPR 2013)
          !!***!
          !!      argA0      = log_mean_size(i)/lavg(i)
          !!      argA0      = log_mean_size(i)
          !!      
          !!     
          !      lesdr = (log_mean_size(i)*exp(log_mean_size(i)) +1.0)/(exp(log_mean_size(i))+exp(-log_mean_size(i)))
          !!      lesdr   = (log_mean_size(i)*exp(log_mean_size(i)) + lavg(i))/(exp(log_mean_size(i))+exp(-log_mean_size(i)))
          !      optimal_prey_sizem   = self%size_offspring + (lesdr-self%size_offspring)*Change_of_optimal_prey_size(i) ! optimal prey size
          !    else
          lesdr   = log_mean_size(i)
          optimal_prey_sizem   = optimal_prey_size(i) ! optimal prey size
          !    endif

          ! Temperature dependency for egg spawning, somatic growth and mortalities 
          if (i .lt. 3) then  !only for i=1,2 aka Beroe Pleurobrachia!!
             !! TODO: refine empirical relationship using Falkenhaug1996 or Finenko2003 data 
             !***!
             log_size_variance_mesozoo(i) = self%sigma * exp(-0.5*(lavg(i)-log_mean_size(i))**2) *(1.0d0-(i-1)*0.2)
             sig(i)    = sqrt(log_size_variance_mesozoo(i))  
             !Temperature_dep(i) = f_Temperature(self%Q10+0.*optimal_prey_size(i), Temperaturep, self%Tc)
             Temperature_dep(i) = f_Temperature(self%Q10, Temperaturep, self%Tc)
             al      = -0.41d0 * (optimal_prey_sizem-lesdr)
             Imax(i) = self%Imax_pot_star *Temperature_dep(i) *  exp( al + (2-al)*(optimal_prey_sizem+lco(i)) +(al-3)*(lesdr+lco(i)) )
          else
             Imax(i) = Temperature_dep(3)
          endif

          ! size derivative of Imax-scaling
          dal_dl(i)     = 0.41d0 * (1.0 - Change_of_optimal_prey_size(i))
          di0_dl(i)  = (al-3) + Change_of_optimal_prey_size(i)*(2-al) + dal_dl(i)*(1.0d0 - optimal_prey_sizem + lesdr)

          !    if (IsMaxIng) then
          !!    if (.true.) then
          !	
          !      dll       = ( (1.0d0+log_mean_size(i))*(exp(log_mean_size(i))*exp(log_mean_size(i))+1.0d0) - (exp(log_mean_size(i))+exp(-log_mean_size(i)))*(log_mean_size(i)*exp(log_mean_size(i))+1.0d0))/(exp(log_mean_size(i))+exp(-log_mean_size(i)))**2
          !      di0_dl(i) = di0_dl(i)* dll
          !    endif

          ! set accumulating stores to zero
          !    graz(i)   = 0.0d0
       end do
       i=99
       ! Temperature experiment; separate effect on parasite dynamics
       !  if( self%OptionOn .and. (Is_Copepod_biomass_negative .or. self%Temperature_Change_Rate .gt. 0.0d0)) then 
       !     Temperaturep  = var(ib)%Temperature + self%Temperature_Change_Rate*exp((mean_Temperature_HR-var(ib)%Temperature)/(2*mean_Temperature_HR))
       !  else
       Temperaturep  = var(ib)%Temperature
       !  endif


       ft2     = f_Temperature(self%Q10,Temperaturep , self%Tc)
       ft      = self%fTDmort/(self%fTDmort+ft2)

       !***!

       ! Dekinga2007/Kraan2008: 16 (1970) - 56 (2005) gAFDW/m2 Wadden Sea
       ! representtive for entire SNS :Heip1992  /16m *0.5 -> 1000 mgC/m3 

       mben=timedefine(var(1)%BenTime)
       !mben=0.0

       mass_sum= ((1*mben + 000.0 + 1*var(ib)%Biomass_Detritus) + mass(1)+ mass(2)+ mass(3) + var(ib)%Biomass_Phytoplankton )*exp(-ft2)!*exp(ft-1)

       do j = 1, 3
          dg_dly(j) = 0.0d0
          mort_graz(j)   = 0.0d0
          ! integration result with Gaussian size distribution (cf. effective prey biomass)
          sig23(j)   = 1.5d0/(1.0d0 + 3*log_size_variance_mesozoo(j))  ! "life-span"=1 : width of life-stage dependent mortality
          sig13(j)   = 1.0d0/sqrt(1.0d0 + 3*log_size_variance_mesozoo(j))
       end do

       ! common variable: most simple detritus pool turnover dynamics 
       ! first the detritus change, as detrivory influences parasites
       ! ---------- calculate RHS  -------------------
       rhsv%Biomass_Detritus   = self%rDet * (mass_sum - var(ib)%Biomass_Detritus)  ! 
       !  ft3(i)        = f_Temperature(self%Q10,Temperaturep, 0.0d0)  ! Temperature dep of quadratic parasite mortality 

       ! Parasite dynamics for each population
       do i = 1, 2 ! loop over parasites
          !this term can only be right for PP
          !    fLc(i)    = exp(-1.5d0*(optimal_prey_size_adult(i)-log_mean_size(3))**2)
          fLc(1)    = exp(-1.5d0*(optimal_prey_size_adult(1)-log_mean_size(2))**2)
          fLc(2)    = exp(-1.5d0*(optimal_prey_size_adult(2)-log_mean_size(3))**2)
          ! abundance of parasite hosts 
          !m_host(1)=mass(1)+fLc(1)*mass(2)
          !m_host(2)=0.8d0*mass(1)+mass(2)+fLc(2)*mass(3)
          m_host(i) = mass(i) + fLc(i)*mass(3)
          !!    m_host(i) = mass(1) +mass(2) + fLc(i)*mass(3)
          ! quadratic parasite mortality 
          ft3(i)       = var(ib)%Biomass_Detritus/self%m_pcap

          !***!
          test0(i)=(ft3(i) * Temperature_dep(3) + no_div_zero_eps)
          rpara(i)  = (self%rParasite * paras(i)) * ((Temperature_dep(3) *m_host(i)/self%m_pcap * ft3(i)) - paras(i)/(ft3(i) * Temperature_dep(3) + no_div_zero_eps))
       end do
       i=99
       rhsv%Parasites_Beroe = rpara(1)
       rhsv%Parasites_PleurobrachiaPileus = rpara(2)
       rhsv%BenTime = 1.0d0/365

       ! ----------  loop over all trophic interactions  -------------------
       !
       !  loop over (ctenophore) predators
       do i = 1, max_number_of_predators
          dp_dl(i)   = 0.0d0
          prey_mass_after_selection_relative_biovolume(i)  = 0.0d0
          prey_mass_after_selection(i)   = 0.0d0
          gross(i)   = 0.0d0
          do j = 1, 3  ! calc total available prey biomass first
             !             if (webtopo(j,i) .gt. 0) then
             if (webtopo(j,i)) then
                dl      = log_mean_size(j) - optimal_prey_size(i)     ! size match to prey
                if(i .eq. 3 .and. dl .gt. 1.5 ) dl = log_mean_size(j) + 2*optimal_prey_size_adult(j) - optimal_prey_size(i)
                ! ingestion kernel
                Ingest_kernel(j)= Imax(i) * exp(-1.5d0 * dl**2)
                ! effective prey mass after integration over selection kernel, with "neutral" selectivity s=3/2
                preyc(j)= sig13(j) * exp(-sig23(j)*dl**2)  
                !     if (i.eq.1 .and. j.eq.3 ) then preyc(j)= 0   Ingest_kernel(j)= 0    endif
                ! reduce cannibalism in Beroe (Hosia2011)     
                ! contribution to consumer size scaling in Imax 
                di_dl(j)= di0_dl(i) + 3*dl*Change_of_optimal_prey_size(i)
                !     preyc(j)= prey_effc(dl2)  ! effective prey mass after integration over selection kernel
                prey_mass_after_selection(i)   = prey_mass_after_selection(i) + preyc(j) * mass(j)  ! effective  prey mass after integration over selection kernel
                prey_mass_after_selection_relative_biovolume(i)   = prey_mass_after_selection_relative_biovolume(i) + preyc(j) * (relDens(j)**0.667) * mass(j)  ! tranformation into -relative- biovolume
             endif
          end do

          ! mortality due to parasites maximal at newly hetched larvae (Hirota1974 ,Greve)
          !   pS(i)      = 1.0d0/(1.0d0+exp((self%Size_Adult-log_mean_size(i))/lavg(i)))
          pS(i)      = 1.0d0/(1.0d0+exp(2*(Size_Adult(i)-log_mean_size(i))))
          ! life-stage dependent mortality due to parasites
          ! fraction of large "meso"zooplakton as suitable parasite host 
          !   mort_P  = self%mP * Temperature_dep(3)**2 *(1.0d0+pS) * (fLc(i)*var(ib)%Biomass_Detritus*1E-3)**2 
          !   bcrit1   = paras(i)/(1.0d0+paras(i)/5E14)
          bcrit1   = paras(i)
          !   bcrit1   = fLc(i)*var(ib)%Biomass_Detritus
          !   bcrit1   = 0.55*(paras(i) + fLc(i)*paras(2))
          !***!
          mort_P(i)  = self%mP * Temperature_dep(3) *(no_age+pS(i)) *bcrit1 ! * 4.0d0/(4.0d0+self%mP * bcrit1)
          ! if (mort_P(i) .gt. 3.0d0 ) write (*,'(A,1(I2),3(F14.3))') 'mp=',i,paras(i),m_host(i),mort_P(i)

          detect=density_disturbance(Size_Adult(1),log_mean_size(3),log_size_variance_mesozoo(3),mass(1),mass(2),mass(3),self%mDisturb)
          ! affinity contains depes on food type (gel), consumer density, Temperature, size(swimming)

          affin(i)    = 1.0d0/self%Bcrit *Temperature_dep(i)* exp(0.5d0*log_mean_size(i))
          !   dummy_reused_variable2      = 0.5*affin(i) * prey_mass_after_selection_relative_biovolume(i) / (self%mR*Temperature_dep(i)*exp(-0.5*log_mean_size(i)))
          ! Temperature dependent loss, with surface-to-volume scaling
          !   mort_R  = self%mR * Temperature_dep(i) * exp(-0.5*log_mean_size(i)+lavg(i)-0*optimal_prey_size(i))!)
          !dummy_reused_variable2 = f_Temperature(self%Q10+0.+ 0.*optimal_prey_size_adult(i), Temperaturep, self%Tc)
          dummy_reused_variable2 = f_Temperature(self%Q10, Temperaturep, self%Tc)
          !   mort_R0(i) = self%mR * Temperature_dep(i) * exp(-0.5*log_mean_size(i)+0*optimal_prey_size_adult(i))!)
          !mort_R0(i) = self%mR * dummy_reused_variable2 * exp(-0.5*log_mean_size(i)-0.*optimal_prey_size_adult(i))!)
	  mort_R0(i) = self%mR * dummy_reused_variable2 * exp(-0.5*log_mean_size(i))
          !***!
          dummy_reused_variable3        = affin(i) * prey_mass_after_selection_relative_biovolume(i) /(mort_R0(i)+no_div_zero_eps)
          !   dummy_reused_variable3      = 2*affin(i) * prey_mass_after_selection_relative_biovolume(i) /(self%mR+no_div_zero_eps)
          activ     = 1.0d0 - exp(-dummy_reused_variable3)
          mort_R(i) = activ * mort_R0(i)
          !   affin   = affin  * dummy_reused_variable3/(1.0d0 + dummy_reused_variable3)log_mean_size(i)
          affin(i)     = affin(i) * activ * exp(-detect*detect) 
          !  loop over prey populations:  1: Beroe 2: Ppileus 3: Copepods
          do j = 1, 3 ! calc total available prey biomass first
             ! if (webtopo(j,i) .gt. 0) then
             if (webtopo(j,i)) then
                ksat(j)    = Ingest_kernel(j)/affin(i)
                preyE      = preyc(j)* mass(j) ! effective prey mass after integration over selection kernel  
                eargA1      = exp(-(affin(i)*prey_mass_after_selection_relative_biovolume(i))/Ingest_kernel(j))

                ! grazing rate (partial gross 2ndary production) of consumer i on prey j
                graz_term(i,j)  = Ingest_kernel(j) * (1.0d0-eargA1) * preyc(j)/(prey_mass_after_selection(i)+no_div_zero_eps) ! * exp(-0*mort_P(i)/Imax(i))
                grazing_pressure_ji(i,j)=graz_term(i,j)*mass(j)

                if (Debugout .and. grazing_pressure_ji(i,j) .gt. 0.5) write (*,'(A,2(I2),F12.4)') 'grazingpressure',i,j,grazing_pressure_ji(i,j) 

                gross(i)      = gross(i)   + grazing_pressure_ji(i,j)
                if (Debugout .and. gross(i) .gt. 1)  write (*,'(A,2(i3),2(F12.4))' ) 'grazing of *i* on *j* is during ** quite large:',i,j,var(1)%BenTime, gross(i)
                mort_graz(j)    = mort_graz(j) + (graz_term(i,j) * mass(i))

                if (Debugout .and. Is_Copepod_biomass_exhausted) write (*,'(A,2(I2),1(F12.4))') 'gr=',i,j,graz_term(i,j)*1E3

                ! update size gradients in grazing rate
                ! size match to selective predation kernel 
                ! derivative of selection kernelexp(-1.5d0*(dl**2))*
                dg_dly(j)  = dg_dly(j) - (log_mean_size(j) - optimal_prey_size(i))* graz_term(i,j)* mass(i) 
                ! affinity term; degree of food limitation (aff=0: g=Imax   aff=Imax: no food)
                aff        = affin(i)*preyE* eargA1  
                ! derivative with respect to prey mass
                dp_dB      = (graz_term(i,j)*(prey_mass_after_selection(i)-preyE)/(preyc(j)+no_div_zero_eps)+(relDens(j)**0.667) *aff)/(prey_mass_after_selection(i)+no_div_zero_eps)
                ! production derivative with respect to consumer size
                !***!
                dp_dl(i)      = dp_dl(i) + (dp_dB*2*sig23(j)*(log_mean_size(j)-optimal_prey_size(i))* Change_of_optimal_prey_size(i))+ (graz_term(i,j)*mass(j)-aff)*di_dl(j) + 0.5*aff
!!! derivative with respect to consumer size (through optimal prey size dependency)     


             else
                grazing_pressure_ji(i,j)=-999.999

             endif
          end do

          !write (*,'(A,2(I2),F12.8)') 'grazingpressure',3,2,grazing_pressure_ji(3,2) 

          ! update all flux stores
          !   graz(i) = graz(i) + gross(i)
          graz(i)     = gross(i) 
          dprod_dl(i) = dp_dl(i)
       end do

       !  loop over dynamic ctenophore populations 
       do i = 1, 2

          ! secondary production  
          ! Biomass_Phytoplanktonsiological/starvation status affects yield (Reeve1989)
          !!   yield_factor    = 1.0d0/(1.0d0+mort_P(i)/(self%yield* graz(i)))
          !!   yield_factor    = exp(-mort_P(i)/(self%yield* graz(i))+no_div_zero_eps)
          !yield_factor(i)     = exp(-2*mort_P(i)/(self%yield* graz(i))+no_div_zero_eps)
          !!   yield_factor    = exp(-mort_P(i)/self%mR)
          yield_factor    = 1.0d0
          prod(i)     = self%yield * yield_factor(i) * graz(i)
          !
          ! ---------- energy losses & mortalities  -------------------
          !

          !       Biomass_Physiological/starvation mortality 
          ! life-stage dependent mortality 
          argA1     = (prod(i)-mort_R(i))/(0*mort_R0(i) + 1*self%mR)!self%mRmort_R* Temperature_dep(i)
          !   argA1   = (prod(i)+mort_R)/(exp(-1.0)*self%mR+no_div_zero_eps) -2.0 -optimal_prey_size_adult(i)
          !   argA1   = (prod(i)-exp(-1.0)*self%mR)/(mort_R(i)+exp(-1.0)*self%mR)
          ft       = self%fTDmort/(self%fTDmort+Temperature_dep(i))

          starv(i)    = exp(-Temperature_dep(i)-argA1)!self%yield *

          mort_S0(i)  = self%mS * starv(i) !*exp(-optimal_prey_size(i))

          mort_S(i)   = mort_S0(i)  *(no_age+pS(i))!*(1.0d0-eS) 

          ! Biomass_Physical damage (turbulence); can be avoided by active swimming
          mort_T0(i)  = self%mT * starv(i) 
          eS0      = sig13(i)* exp(-sig23(i)*(Size_Adult(i)-log_mean_size(i))**2)
          mort_T(i)   = mort_T0(i) * (1.0d0 - eS0) 

          ! --------  energy/carbon partitioning to egg production/somatic growth  ------------
          !
          !  how far way are juveniles from maturity ? 
          argA2     = (Size_Maturity(i)-log_mean_size(i))/(sqrt(2.d0)*sig(i))

          ! errf     = (1-exp(-argA2*2.45d0))/(1+exp(-argA2*2.45d0)) !error function
          errf=errfunc(argA2)

          ! relative fraction of adults 
          fA(i)       = 0.5d0*(1.0d0 - errf) 

          argA5     = (self%Size_Observable-log_mean_size(i))/(sqrt(2.d0)*sig(i))
          errf1=errfunc(argA5)
          fObs(i)       = 0.5d0*(1.0d0 - errf1) 
          biomass_observable(i)=fObs(i)*mass(i)

          ! size derivative of adult fraction
          !   dfA_dl= sqrt(2.d0*3.1415)/sig(i) * eargA1
          ! mean adult size
          eargA2    = exp(- argA2*argA2)
          !  if (eargA2 .gt. 1.2 .or. eargA2 .lt. 0.0001) write (*,'(A,1(I2),5(F12.5))') 'fA=',i,log_mean_size(i),sig(i) ,argA2,eargA2, fA 

          lm_adult = log_mean_size(i) + sig(i) / sqrt(2.d0*3.1415) * eargA2 / (abs(fA(i))+0.05d0)

          ! fraction of adult secondary production allocated to recruitment
          !***!
          fR       = 0.75d0*Temperature_dep(i)

          ! rate at which adults spawn new eggs
          recruit(i)  = fA(i) * fR * prod(i)

          ! somatic growth : TODO: Temperature dependency
          somgrwth(i) = prod(i) - recruit(i) - mort_R(i)  ! can become negative which is OK

          if (TopPredationSwitch) then
             ! top-down pressure by larger jellies (cnidariaarians such as Aurelia Cyanea, or Chrysaora)
             ! TODO: why was the mass cut out from this??
             mort_top(i) = Temperature_dep(3)*self%m_predBe  * cnidaria *mass(i)    !* mass(i)
          else
             mort_top(i)=0.0d0
          endif

	  !constant mortalilty experient
          if (self%ConstMortExp) then
             mort_const(i)=self%mC
          !   write(*,*) 'constant mortalilty experient',self%mC
          else 
             mort_const(i)=0.0d0
          endif
          
          if (self%LowTempMort) then
             if (var(ib)%Temperature<self%mTempT) then
               mort_Temp(i)=self%mTemp
             else 
               mort_Temp(i)=0.0d0
             endif
          else 
            mort_Temp(i)=0.0d0
          endif


          !  sum of all mortality rates
          mort_sum(i) = mort_R(i) + mort_S(i)  + mort_graz(i)+ mort_P(i) + mort_top(i)+ mort_T(i) + mort_const(i) + mort_Temp(i)


          ! ----------  stage and size dynamics  -------------------
          !
          if (self%SizeDynOn) then
             ! egg production related part of size dynamics 
             init_dl(i)  = (self%size_offspring - lm_adult) * recruit(i)

             ! somatic growth related part of size dynamics 
             som_dl(i)   = somgrwth(i)/3

             ! marginal size shift due to selective grazing at neutral kernel width
             !   shifts prey distribution away from l_opt_pred, thus to lower mortality
             graz_dl(i)  = -log_size_variance_mesozoo(i) * dg_dly(i)

             !  marginal size shift due to senescence

             ! size derivative 
             dummy_reused_variable4       = 2 * pS(i)**2 * exp(2*(Size_Adult(i)-log_mean_size(i)))/(no_div_zero_eps+no_age+pS(i))
             sen_dl(i)   = -log_size_variance_mesozoo(i) *  mort_S0(i) * dummy_reused_variable4

             !  marginal size shift due to respiration and turbulence (same scaling exponent)

             turb_dl(i)  = log_size_variance_mesozoo(i) * mort_T0(i) * eS0 *2*sig23(i)* (Size_Adult(i)-log_mean_size(i))

             resp_dl(i)  = log_size_variance_mesozoo(i) * mort_R(i) * 0.5*(1+0*Change_of_optimal_prey_size(i))

             !  marginal size shift due to density dependent mortality (parasites)

             paras_dl(i) = -log_size_variance_mesozoo(i) * mort_P(i) * dummy_reused_variable4

             dummy_reused_variable5       = fA(i)*fR + mort_R(i)/(prod(i)+no_div_zero_eps) + 0.
             if(dummy_reused_variable5 .lt. 1.0d0) then
                prod_dl(i)  = log_size_variance_mesozoo(i) * self%yield*yield_factor(i) * (1.0d0 - dummy_reused_variable5) * dprod_dl(i)
             else
                prod_dl(i)  = 0.0d0
             endif

             !  sum of productivity related size selective forces
             sum_dl(i)   = init_dl(i) + som_dl(i) + prod_dl(i) + resp_dl(i) 
             !***!

             ! boundary condition of offspring production and adaptive size shift
             argA3     = (self%size_offspring-log_mean_size(i))/(sqrt(2.d0)*sig(i))
             min_dl(i)   = -recruit(i) * exp(argA3**2) * sig(i) / sqrt(2.d0*3.1415)
             if (sum_dl(i) .lt. min_dl(i) ) then 
                bound_dl(i) = min_dl(i)-sum_dl(i)
             else
                bound_dl(i) = 0.0
             endif
             sum_dl(i)   = sum_dl(i) + bound_dl(i)
             !  sum of all size selective forces
             sum_dl(i)  = sum_dl(i) + graz_dl(i) + sen_dl(i) +  turb_dl(i) + paras_dl(i)
          else
             sum_dl(i)  = 0.0d0
             graz_dl=-999
             sen_dl=-999
             turb_dl=-999
             paras_dl=-999
             som_dl=-999
             prod_dl=-999
             resp_dl=-999
             init_dl=-999
             dummy_reused_variable5=-999
          endif

          !#S__RHS
          !#E__RHS
          !---------- RHS for each state variable ----------
          if (i .eq. 1) then ! Beroe
             ! --- dynamics of Beroe biomass
             ! quadratic mortality of Beroe to emulate top-down closure

             rhsv%Biomass_Beroe = (prod(i) - mort_sum(i) )* var(ib)%Biomass_Beroe + Temperature_dep(1)*self%immigr
             ! --- dynamics of Beroe mean log size
             !  immigration  of mature individuals only

             rhsv%Size_Beroe = sum_dl(i) 

             ! Export diagnostic variables
             if (ib.eq.1) then

                _SET_DIAGNOSTIC_(self%id_prod_Be, prod(i))                   !step_integrated secondary production rate Beroe
                _SET_DIAGNOSTIC_(self%id_Mort_Be, mort_sum(1))               !step_integrated mortality rate of Beroe
                _SET_DIAGNOSTIC_(self%id_fA_Be, fA(i))                       !step_integrated relative propotion adults Beroe
                _SET_DIAGNOSTIC_(self%id_Imax_Be, Imax(1))        !step_integrated maximum ingestion rate adult Beroe
                _SET_DIAGNOSTIC_(self%id_al_Im_Be, fLc(i))              !step_integrated size scaling expoentent Imax 
                _SET_DIAGNOSTIC_(self%id_optimal_prey_size_Be, optimal_prey_size(1))                !step_integrated optimum prey size Beroe

                _SET_DIAGNOSTIC_(self%id_som_dl_Be, som_dl(i))                  !step_integrated marginal size shift due to promotion
                _SET_DIAGNOSTIC_(self%id_init_dl_Be, init_dl(i))                !step_integrated marginal size shift due to egg production
                _SET_DIAGNOSTIC_(self%id_graz_dl_Be, graz_dl(i))                !step_integrated marginal size shift due to selective grazing
                _SET_DIAGNOSTIC_(self%id_sen_dl_Be, sen_dl(i))                  !step_integrated marginal size shift due to starvation 
                ! TODO:????
                _SET_DIAGNOSTIC_(self%id_turb_dl_Be, turb_dl(i))                  !step_integrated marginal size shift due to physical damage 

                _SET_DIAGNOSTIC_(self%id_prod_dl_Be, prod_dl(i))                !step_integrated marginal size shift due to production 
                _SET_DIAGNOSTIC_(self%id_resp_dl_Be, resp_dl(i))                !step_integrated marginal size shift due to respiration 
                _SET_DIAGNOSTIC_(self%id_paras_dl_Be, paras_dl(i))              !step_integrated marginal size shift due to parasitism 
                _SET_DIAGNOSTIC_(self%id_dl_prey_Be, dg_dly(i))                !step_integrated size difference to prey 
                _SET_DIAGNOSTIC_(self%id_dl_pred_Be, dprod_dl(i))                 !step_integrated size difference to pred 
                _SET_DIAGNOSTIC_(self%id_mort_P_Be, mort_P(i))                  !step_integrated density dependent mortality - parasites
                _SET_DIAGNOSTIC_(self%id_mort_S_Be, mort_S(i))                  !step_integrated Biomass_Phytoplanktonsiological adult mortality rate
                _SET_DIAGNOSTIC_(self%id_mort_R_Be, mort_R(i))                  !step_integrated Temperature dependent mortality
                _SET_DIAGNOSTIC_(self%id_mort_G_Be, mort_graz(i))                  !step_integrated top-predation

                _SET_DIAGNOSTIC_(self%id_mort_top_Be,mort_top(i))

                ! TODO:???
                !_SET_DIAGNOSTIC_(self%id_mort_J_Be, mben)                  !step_integrated juvenile mortality
                _SET_DIAGNOSTIC_(self%id_mort_T_Be, mort_T(i))                !step_integrated damaging effect of turbulence 

                _SET_DIAGNOSTIC_(self%id_somgrowth_Be, somgrwth(i))             !step_integrated somatic growth rate 
		! TODO:???
                _SET_DIAGNOSTIC_(self%id_recruit_Be, recruit(i))                !recruitstep_integrated egg production rate 
                !_SET_DIAGNOSTIC_(self%id_mixBmass_Be,m_host(i))            !step_integrated mass exchange rate Coast-HR-Offshore 
                !_SET_DIAGNOSTIC_(self%id_mixlsize_Be, mass(3))           !dTrait(2,1)step_integrated trait exchange rate Coast-HR-Offshore
                _SET_DIAGNOSTIC_(self%id_Tdep_Be, Temperature_dep(i))                  !step_integrated Temperature dependence

                _SET_DIAGNOSTIC_(self%id_dummy1, m_host(1)) 
                _SET_DIAGNOSTIC_(self%id_dummy3, test0(1)) 
                _SET_DIAGNOSTIC_(self%id_dummy5, dummy_reused_variable5) 
                _SET_DIAGNOSTIC_(self%id_dummy6, graz(1)) 
                _SET_DIAGNOSTIC_(self%id_dummy8, yield_factor(1)) 


             endif
             ! TODO : elseif (i .eq. 2)then
          else  !  P.Pileus
             ! --- dynamics of P.Pileus biomass
             rhsv%Biomass_PleurobrachiaPileus = (prod(i) - mort_sum(2)) * var(ib)%Biomass_PleurobrachiaPileus + Temperature_dep(2)*self%immigr
             ! --- dynamics of P.Pileus mean log size
             rhsv%Size_PleurobrachiaPileus = sum_dl(i) 

             ! Export diagnostic variables
             if (ib.eq.1) then
                _SET_DIAGNOSTIC_(self%id_prod_Pp, prod(i))                   !step_integrated secondary production rate P pileus
                _SET_DIAGNOSTIC_(self%id_Mort_Pp, mort_sum(2))               !step_integrated mortality rate of P pileus
                _SET_DIAGNOSTIC_(self%id_fA_Pp, fA(i))                       !step_integrated relative propotion adults P pileus
                _SET_DIAGNOSTIC_(self%id_Imax_Pp, Imax(2))                !step_integrated maximum ingestion rate adult Beroe
                _SET_DIAGNOSTIC_(self%id_al_Im_Pp, fLc(i))              !step_integrated size scaling expoentent Imax 
                _SET_DIAGNOSTIC_(self%id_optimal_prey_size_Pp, optimal_prey_size(2))                !step_integrated optimum prey size Beroe

                _SET_DIAGNOSTIC_(self%id_som_dl_Pp, som_dl(i))                  !step_integrated marginal size shift due to promotion
                _SET_DIAGNOSTIC_(self%id_init_dl_Pp, init_dl(i))                !step_integrated marginal size shift due to egg production
                _SET_DIAGNOSTIC_(self%id_graz_dl_Pp, graz_dl(i))                !step_integrated marginal size shift due to selective grazing
                _SET_DIAGNOSTIC_(self%id_sen_dl_Pp, sen_dl(i))                  !step_integrated marginal size shift due to starvation 
                ! TODO:????
                _SET_DIAGNOSTIC_(self%id_turb_dl_PP, turb_dl(i))                  !step_integrated marginal size shift due to physical damage 

                _SET_DIAGNOSTIC_(self%id_prod_dl_Pp, prod_dl(i))                !step_integrated marginal size shift due to production 
                _SET_DIAGNOSTIC_(self%id_resp_dl_Pp, resp_dl(i))                !step_integrated marginal size shift due to respiration 
                _SET_DIAGNOSTIC_(self%id_paras_dl_Pp, paras_dl(i))              !step_integrated marginal size shift due to parasitism 
                _SET_DIAGNOSTIC_(self%id_dl_prey_Pp, dg_dly(i))                !step_integrated size difference to prey 
                _SET_DIAGNOSTIC_(self%id_dl_pred_Pp, dprod_dl(i))                 !step_integrated size difference to pred 
                _SET_DIAGNOSTIC_(self%id_mort_P_Pp, mort_P(i))                  !step_integrated density dependent mortality - parasites
                _SET_DIAGNOSTIC_(self%id_mort_S_Pp, mort_S(i))                  !step_integrated Biomass_Phytoplanktonsiological adult mortality rate
                _SET_DIAGNOSTIC_(self%id_mort_R_Pp, mort_R(i))                  !step_integrated Temperature dependent mortality
                _SET_DIAGNOSTIC_(self%id_mort_G_Pp, mort_graz(i))                  !step_integrated top-predation

                _SET_DIAGNOSTIC_(self%id_mort_top_Pp,mort_top(i))
                ! TODO:???
                !_SET_DIAGNOSTIC_(self%id_mort_J_Pp, mben)                  !step_integrated juvenile mortality
                _SET_DIAGNOSTIC_(self%id_mort_T_Pp, mort_T(i))                !step_integrated damaging effect of turbulence 

                _SET_DIAGNOSTIC_(self%id_somgrowth_Pp, somgrwth(i))             !step_integrated somatic growth rate 
		! TODO:???
                _SET_DIAGNOSTIC_(self%id_recruit_Pp, recruit(i))                !recruitstep_integrated egg production rate 
                !_SET_DIAGNOSTIC_(self%id_mixBmass_Pp,m_host(i))            !step_integrated mass exchange rate Coast-HR-Offshore 
                !_SET_DIAGNOSTIC_(self%id_mixlsize_Pp, mass(3))           !dTrait(2,1)step_integrated trait exchange rate Coast-HR-Offshore
                _SET_DIAGNOSTIC_(self%id_Tdep_Pp, Temperature_dep(i))                  !step_integrated Temperature dependence
                _SET_DIAGNOSTIC_(self%id_cnidaria, cnidaria)                  !step_integrated marginal size shift due to physical damage 


                _SET_DIAGNOSTIC_(self%id_dummy2, m_host(2)) 
                _SET_DIAGNOSTIC_(self%id_dummy4, test0(2)) 
                _SET_DIAGNOSTIC_(self%id_dummy7,graz(2)) 
                _SET_DIAGNOSTIC_(self%id_dummy9,yield_factor(2)) 
             endif
          endif

          _SET_DIAGNOSTIC_(self%id_grazingpressure1, grazing_pressure_ji(1,1) )  
          _SET_DIAGNOSTIC_(self%id_grazingpressure2, grazing_pressure_ji(1,2) ) 
          _SET_DIAGNOSTIC_(self%id_grazingpressure3, grazing_pressure_ji(1,3) ) 

          _SET_DIAGNOSTIC_(self%id_grazingpressure4, grazing_pressure_ji(2,1) ) 
          _SET_DIAGNOSTIC_(self%id_grazingpressure5, grazing_pressure_ji(2,2) ) 
          _SET_DIAGNOSTIC_(self%id_grazingpressure6, grazing_pressure_ji(2,3) ) 

          _SET_DIAGNOSTIC_(self%id_grazingpressure7, grazing_pressure_ji(3,1) ) 
          _SET_DIAGNOSTIC_(self%id_grazingpressure8, grazing_pressure_ji(3,2) ) 
          _SET_DIAGNOSTIC_(self%id_grazingpressure9, grazing_pressure_ji(3,3) ) 

          _SET_DIAGNOSTIC_(self%id_sig1, sig(1) )  
          _SET_DIAGNOSTIC_(self%id_sig2, sig(2) ) 
          _SET_DIAGNOSTIC_(self%id_sig3, sig(3) ) 

          _SET_DIAGNOSTIC_(self%id_ObsMass1, biomass_observable(1) )  
          _SET_DIAGNOSTIC_(self%id_ObsMass2, biomass_observable(2) ) 
          _SET_DIAGNOSTIC_(self%id_ObsMass3, biomass_observable(3) )

         _SET_DIAGNOSTIC_(self%id_dummy11,  rhsv%Biomass_PleurobrachiaPileus)  
         _SET_DIAGNOSTIC_(self%id_dummy12,  rhsv%Parasites_PleurobrachiaPileus)  
         _SET_DIAGNOSTIC_(self%id_dummy13, mben)  
         _SET_DIAGNOSTIC_(self%id_dummy14, mass_sum)
         _SET_DIAGNOSTIC_(self%id_dummy15,log_mean_size(3))
         _SET_DIAGNOSTIC_(self%id_dummy16,prod(1) - mort_sum(1))
         _SET_DIAGNOSTIC_(self%id_dummy17,prod(2) - mort_sum(2))
 !_SET_DIAGNOSTIC_(self%id_dummy18,)
 !_SET_DIAGNOSTIC_(self%id_dummy19, )

!         _SET_DIAGNOSTIC_(self%id_Copepods, var(ib)%Copepods)  ! biomass from Greve data-set
!         _SET_DIAGNOSTIC_(self%id_Size_Copepods, var(ib)%Size_Copepods)  ! biomass from Greve data-set
!         _SET_DIAGNOSTIC_(self%id_Temperature, var(ib)%Temperature)  ! Temperature HR!
!         _SET_DIAGNOSTIC_(self%id_Biomass_Phytoplankton, var(ib)%Biomass_Phytoplankton)  ! Biomass_Phytoplanktontoplankton biomass HR


          !write (*,'(1(F10.6))')   ftd/ntd 
          !#S__DIA
          !#E__DIA
       end do



       ! ------------------------------------------------------------------------------
       !#S_ODE
       !---------- ODE for each state variable ----------
       _SET_ODE_(self%id_Biomass_PleurobrachiaPileus, rhsv%Biomass_PleurobrachiaPileus UNIT)
       _SET_ODE_(self%id_Size_PleurobrachiaPileus, rhsv%Size_PleurobrachiaPileus UNIT)
       _SET_ODE_(self%id_Biomass_Beroe, rhsv%Biomass_Beroe UNIT)
       _SET_ODE_(self%id_Size_Beroe, rhsv%Size_Beroe UNIT)
       _SET_ODE_(self%id_Biomass_Detritus, rhsv%Biomass_Detritus UNIT)
       _SET_ODE_(self%id_Parasites_PleurobrachiaPileus, rhsv%Parasites_PleurobrachiaPileus UNIT)
       _SET_ODE_(self%id_Parasites_Beroe, rhsv%Parasites_Beroe UNIT)
       _SET_ODE_(self%id_BenTime, rhsv%BenTime UNIT)
       !#E_ODE
    end do
    ! Leave spatial loops (if any)
    !_FABM_LOOP_END_
    _LOOP_END_

  end subroutine do
  !EOC

  ! ------------------------------------------------------------------------------
  pure real(rk) function grazkinetics(bcrit,preye)
    implicit none
    real(rk), intent(in)      :: bcrit, preye

    grazkinetics = 1.0d0-exp(-preye/bcrit)
  end function grazkinetics

  ! ------------------------------------------------------------------------------
  ! effective prey after integration over selection kernel  (Wirtz, Mno_div_zero_eps 2014)
  pure real(rk) function prey_effc(dl2)
    implicit none
    real(rk), intent(in)      :: dl2
    prey_effc     = sqrt(i13sig) * exp(-dl2*i13sig)
  end function prey_effc

  ! ------------------------------------------------------------------------------
  pure real(rk) function grazrate(dl2,Imax0, bcrit, prey)
    implicit none
    real(rk), intent(in)      :: dl2, Imax0, bcrit, prey
    !   real(rk)   :: dl2
    grazrate = Imax0  * exp(-dl2) * grazkinetics(bcrit,prey) 

  end function grazrate

  ! ------------------------------------------------------------------------------
!!Temperature response function which uses a Q10 approach with cutoff at mini
  pure real(rk) function f_Temperature(q10,T,T_c)
    implicit none
    real(rk), intent(in)      :: q10,T,T_c
    !  real(rk)   :: q2
    !   q2      = q10**2
    !   f_Temperature  = 1.0d0/(q2 * exp(-T*q10/30)+ exp(-q2*(T-T_c)))
    f_Temperature  = 1.0d0/(exp(-(T-15.0d0)*0.1*log(q10))+ exp(-exp(1+q10)*(T-T_c)*0.1) )

  end function f_Temperature

  ! ------------------------------------------------------------------------------
!! Temperature response function
  pure real(rk) function e_Temperature(T,T_c)
    implicit none
    real(rk), intent(in)      :: T,T_c

    e_Temperature  = 1.0d0/(1.0d0+ exp((T-T_c)/2+1.0d0) )
    !   e_Temperature  = exp(-T**2/(2*T_c**2))
    !   e_Temperature  = 0.1d0 + 0.9d0/(1.0d0+ exp(1*(T-T_c)) )

    !0.1+0.9./(1+exp(2*(T-T_c)));
  end function e_Temperature

  ! ------------------------------------------------------------------------------
 
  pure real(rk) function errfunc(arg)
    implicit none
    ! !INPUT PARAMETERS:
    real(rk), intent(in)      :: arg
    errfunc  = (1-exp(-arg*2.45d0))/(1+exp(-arg*2.45d0))
  end function errfunc


!this function provides additional predatoion pressure based on observation data. As these data is derived from annual averages, we cannot read it in from file, since special interpolation is needed.
  pure real(rk) function additional_food(btime)
    implicit none
    real(rk),intent(in) :: btime
    real(rk),dimension(51) :: mAurelia60,mCyanea60
    real(rk) :: reltim,cnidaria
    integer::yi

 ! annual TS abundance data for scyphomedusae from VanWalraven et al 2014 
    mAurelia60 =(/ 2.133,0.213,0.000,7.253,0.000,0.213,0.213,0.427,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.640,0.000,0.000,72.960,0.427,30.080,47.787,10.667,0.853,20.053,77.013,9.387,24.960,6.400,10.667,9.387,31.147,26.667,16.427,4.267,29.227,4.693,7.253,2.133,0.640,0.427,4.053,7.893,12.587,0.213,0.000,0.000,27.733,3.840,0.213,22.613 /)
    mCyanea60  =(/ 0.033,0.000,0.000,0.780,0.423,0.195,0.033,0.553,0.033,0.000,0.000,0.748,1.301,0.065,2.211,0.325,0.585,0.228,0.033,0.033,0.325,5.236,0.358,0.423,0.520,9.138,2.699,0.585,1.528,1.691,5.463,2.472,0.065,3.089,1.203,0.195,10.862,0.748,0.358,0.423,0.260,0.455,1.789,6.667,1.203,0.390,2.146,11.740,1.171,0.098,0.618 /)

    !if (btime .lt. 7.4d0) then   cnidaria = 1.0d0
    !else   cnidaria = 5.0d0 endif

    yi = FLOOR(btime)  ! year index relative to 1960
    reltim      = btime - yi - 0.56 ! peak abundance around day 200
    reltim      = reltim / 0.22  
    if (yi+14 .lt. 51) then
       cnidaria = (mAurelia60(yi+14)+mCyanea60(yi+14))* exp(-reltim**2)
    else
       cnidaria = 0.0d0
    endif
    additional_food=cnidaria
  end function additional_food

  pure real(rk) function prey_development(experimental_optimal_prey_size_adult,size_offspring,Size_Adult)
    implicit none
    real(rk),intent(in) :: experimental_optimal_prey_size_adult,size_offspring,Size_Adult
    prey_development=(experimental_optimal_prey_size_adult-size_offspring)/(Size_Adult-size_offspring) 
  end function prey_development


  pure real(rk) function density_disturbance(Size_Adult,log_mean_size3,log_size_variance_mesozoo3,mass1,mass2,mass3,mDisturb)
    implicit none
    !real(rk),dimension(3),intent(in): Size_Adult
    real(rk),intent(in) :: Size_Adult,log_mean_size3,log_size_variance_mesozoo3,mass1,mass2,mass3,mDisturb
    real(rk) ::detect,dummy_reused_variable0
    ! consumer density reduces food visibility
    !lets use PP size for now
    dummy_reused_variable0      = 1.*exp(-(Size_Adult-log_mean_size3)**2/(2*log_size_variance_mesozoo3)) * mass3

    detect  = (mass1+mass2+dummy_reused_variable0)/mDisturb !*exp(log_mean_size(i)-optimal_prey_size(i))

    density_disturbance=detect
  end function density_disturbance

  pure real(rk) function timedefine(BenTime)
    implicit none
    real(rk),intent(in)::BenTime
    real(rk)::mben
    mben = 850.0d0
    if (BenTime .lt. 6.0d0) then
       mben = 700.0d0
    else
       if (BenTime .lt. 17.0d0) then
          mben = 950.0d0
       else
          mben = 950.0d0+(BenTime-17.0d0) * 50.0d0
       endif
    endif
    timedefine=mben
  end function timedefine

  !EOC
end module hzg_ctenophore_jt
!:#endif
